/* Events to emmit */
module.exports = {
  COMMUNITY_CHAT: 'COMMUNITY CHAT',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SET',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT'
};
